Repository jellyfin/jellyfin-plugin-tvdb, pull requests merged in 2024-02, with the labels that each got.

#93 Tvdb v4 migration
  Jellyfin.Plugin.Tvdb/Configuration/PluginConfiguration.cs
  Jellyfin.Plugin.Tvdb/Configuration/config.html
  Jellyfin.Plugin.Tvdb/Jellyfin.Plugin.Tvdb.csproj
  Jellyfin.Plugin.Tvdb/Providers/TvdbEpisodeImageProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbEpisodeProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbMissingEpisodeProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbPersonImageProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbSeasonImageProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbSeriesImageProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbSeriesProvider.cs
  Jellyfin.Plugin.Tvdb/TvdbClientManager.cs
  Jellyfin.Plugin.Tvdb/TvdbCultureInfo.cs
  Jellyfin.Plugin.Tvdb/TvdbUtils.cs
  Jellyfin.Plugin.Tvdb/countries.json
  Jellyfin.Plugin.Tvdb/iso6392.txt
  build.yaml
Labels: major-feature

#108 Don't require user pin
  Jellyfin.Plugin.Tvdb/TvdbClientManager.cs
Labels: bug

#113 Update to Tvdb sdk 4.7.9.1
  Jellyfin.Plugin.Tvdb/Jellyfin.Plugin.Tvdb.csproj
  Jellyfin.Plugin.Tvdb/Providers/TvdbEpisodeProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbMissingEpisodeProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbPersonImageProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbSeriesProvider.cs
  Jellyfin.Plugin.Tvdb/TvdbClientManager.cs
  Jellyfin.Plugin.Tvdb/TvdbUtils.cs
Labels: bug

#112 Make Tvdb Client usage more resilient and robust
  Jellyfin.Plugin.Tvdb/CollectionExtensions.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbEpisodeImageProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbSeasonImageProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbSeriesImageProvider.cs
  Jellyfin.Plugin.Tvdb/Providers/TvdbSeriesProvider.cs
  Jellyfin.Plugin.Tvdb/TvdbSdkExtensions.cs
  Jellyfin.Plugin.Tvdb/TvdbUtils.cs
Labels: chore
